############# Turn on movement light in comp room #####################
- alias: Turn on comp room light on movement
  trigger:
    platform: state
    entity_id: binary_sensor.comp_room_ms
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.comp_room_light

- alias: Turn off comp room light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.comp_room_ms
    to: 'off'
    for:
      minutes: 10
  action:
    service: switch.turn_off
    entity_id: switch.comp_room_light
