- alias: DoorBell_Trigger
  trigger:
    platform: mqtt
    topic: RF433/data
  condition:
  - condition: template
    value_template: >
      {{ trigger.payload[:9]=='{"rfin":"' and trigger.payload[21:27]=='810208' }}
  action:
    service: mqtt.publish
    data:
      topic: "zoneminder/doorbell"
      payload: "bell"

# 2fl dis  FB7891         
# doorbell 810208

- alias: mqttDoorbell
  trigger:
    platform: mqtt
    topic: "zoneminder/doorbell"
  action:
    service: notify.doorbell_ring
    data:
      title: "Door Bell Camera"
      message: "Entry Door Bell"

- alias: mqttEntryDoorMotion
  trigger:
    platform: mqtt
    topic: "zoneminder/10"
  condition:
    condition: template  
    value_template: > 
      {{ as_timestamp(now()) - 
      (as_timestamp(states.automation.mqttentrydoormotion.attributes.last_triggered)
       | default(0)) | int > 60 }}
  action:
    service: notify.doorbell_motion
    data:
      title: "Door Bell Camera"
      message: "Entry Door Motion Detected"
# note: notify service can't be called without data part
# keep at least title or message here





