########## hw pump script: turn on hw_remotes on ############3        
- alias: a_turn_hw_on
  trigger:
    platform: state
#    to: 'on'
    entity_id: binary_sensor.hw_rem_fridge,binary_sensor.hw_rem_2floor,binary_sensor.hw_rem_mb 
  action:
    - service: script.turn_on
#      entity_id: script.turn_hw_on_scr
      data_template:
        entity_id: 'script.s_turn_hw_{{trigger.to_state.state}}'
#        entity_id: >
#          {% if is_state('trigger.to_state', 'on') %}
#          script.turn_hw_on_scr
#          {% else %}
#          script.turn_hw_off_scr
#          {% endif %}
      
    - service: notify.file_notify
      data_template:  
        message: >
          {{now().strftime("%d-%H:%M:%S")}} trg state from {{ trigger.from_state.state }}
          to {{ trigger.to_state.state }}
          script.s_turn_hw_{{trigger.to_state.state}}

  
  ########  turn off on hw_remotes off    
- alias: a_turn_hw_off
  trigger:
    platform: state
    entity_id: group.hw_remotes
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.hw_pump
    - service: script.turn_off
      entity_id: script.hw_set_timer 
######## Turn on hw pump on schedule ###############
#### work days
- alias: hw on workday
  trigger:
    - platform: time
      at: '5:20'
    - platform: time
      at: '5:55'
    - platform: time
      at: '20:30'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed 
    - thu
    - fri
  action:
    service: script.s_turn_hw_on
### weekend  
- alias: hw on weekend
  trigger:
    - platform: time
      at: '6:55'
    - platform: time
      at: '20:30'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
    service: script.s_turn_hw_on
