### outdoor lights  
- alias: turn outdoor lights on
  trigger:
    platform: sun
    event: sunset
    offset: "00:15:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_lights

- alias: turn outdoor lights off
  trigger:
    platform: time
    at: '22:00:00'

#    platform: sun
#    event: sunset
#    offset: "03:15:00"
          
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_lights
################## scheduled arm/disarm security_panel  ###############
- alias: sec_arm_home 22:30
  trigger:
    platform: time
    at: '22:30:00'
  condition: 
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: disarmed

  - condition: time
    weekday:
      - sun
      - mon
      - tue
      - wed 
      - thu
      - fri
      - sat
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.ha_alarm
    - service:    variable.set_variable 
      data:
        variable: alarm_panel_changedby  
        value: 'scheduler'

### scheduled disarm
- alias: sec_disarm 5:25
  trigger:
    platform: time
    at: '05:25:00'
  condition:  
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home

  - condition: time
    weekday:
    - mon
    - tue
    - wed 
    - thu
    - fri
    - sat
    - sun
  action:
    - service:    variable.set_variable 
      data:
        variable: alarm_panel_changedby  
        value: 'scheduler'
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm


