###### Version 2 - calls py scripts ######
# or_remote_event, on_sensor_event, on_alarm_state_change
########### REMOTES Events ##########
- alias: Remote Button Pressed
  trigger:
    platform: event
    event_type: 'remote_button'
  action:
  - service: python_script.on_remote_event
    data_template: 
        button: "{{trigger.event.data.button}}"
        remote: "{{trigger.event.data.rem}}"

- alias: Sensor Event
  trigger:
    platform: event
    event_type: 'sensor_state'
  condition:
    condition: and
    conditions:
      - condition: or 
        conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_home
      - condition: template
        value_template: '{{trigger.event.data.state=="on"}}'
  
  action: 
  - service: python_script.on_sensor_on
    data_template: 
        sensor: "{{trigger.event.data.snr}}"
        state: "{{trigger.event.data.state}}"

- alias: security_panel state
  trigger: 
    platform: state
    entity_id: alarm_control_panel.ha_alarm
  action: 
  - service: python_script.on_alarm_panel_state_change
    data_template: 
        from_state: "{{trigger.from_state.state}}"
        to_state: "{{trigger.to_state.state}}"

- alias: sec_sensor_door_chime
  trigger:
    platform: event
    event_type: door_snr_chime
  action:
    service: script.door_snr_chime


  